### ISSUE TITLE
org.ysb33r.nodejs.npm not published on https://plugins.gradle.org

### ISSUE THREAD

**Issue by cyrillzadra** [ysb33r/nodejs-gradle-plugin#3]
Hi there 

Tried out your new nodejs plugin and it seems org.ysb33r.nodejs.npm plugin is not yet published on https://plugins.gradle.org/ . 

> plugins {
>   id "org.ysb33r.nodejs.base" version "0.1"
>   id 'org.ysb33r.nodejs.npm'   version '0.1'
> }
> 

> C:\dev\ie-git\webclient>gradlew tasks
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'C:\dev\ie-git\webclient\tsclient\build.gradle' line: 4
> 
> * What went wrong:
> Plugin [id: 'org.ysb33r.nodejs.npm', version: '0.1'] was not found in any of the following sources:
> 
> - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
> - Gradle Central Plugin Repository (no 'org.ysb33r.nodejs.npm' plugin available - see https://plugins.gradle.org for available plugins)
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED in 4s

base and gulp the can be found. -> https://plugins.gradle.org/search?term=ysb33r+nodejs

I'm looking forward testing in nodejs-plugin few more hours. 

regards
cyrill

**Comment by ysb33r** [comment]
Grrr... Will get it fixed. In the mean-time apply `org.ysb33r.nodejs.gulp` as a workaround.

**Comment by ysb33r** [comment]
Fixed. Please check if it works for you now.

**Comment by cyrillzadra** [comment]
Thanks ... it does work now. 👍
